### PR TITLE
relax oauth dependency

### PR DESCRIPTION
**Pull request by wjordan**
The `oauth` gem was recently updated from `0.4.x` to `0.5.x`, which contains a fix to oauth-xx/oauth-ruby#13 which is necessary to use this library with Rails 5. This PR relaxes the `oauth` dependency to allow this library to be used with the newer `0.5.x` versions of that dependency.

### CODE REVIEW

**Comment by bracken** [comment]
Seems like a good idea, would just need some perusing of the change log and some testing probably.

**Comment by wjordan** [comment]
I added some extra commits to update `Gemfile`/`gemspec` to actually run/pass the existing test suite against the latest oauth `0.5.x` gem (currently `0.5.1`). The [changelog](https://github.com/oauth-xx/oauth-ruby/blob/master/HISTORY) doesn't indicate any notable API-breaking changes, only fixes and compatibility updates (last release of `0.4.x` was in 2012).

**Comment by jbasdf** [comment]
Any chance this could be merged in? The readme states:

# For a Rails 5 (and 2.3) app:
require 'oauth/request_proxy/action_controller_request'

However, it doesn't work with Rails 5. You will get the following error:
`require': cannot load such file -- action_controller/request (LoadError)

In order for this to work properly we need to upgrade to the 0.5.x version of the oauth gem.

**Comment by bracken** [comment]
I rebased, tested, and merged it, but I can't cut a new gem. Only someone like @rivernate can do that.

**Comment by rivernate** [comment]
I've pushed up 1.1.13 to rubygems, with the merged changes

**Pull request closed without merging**
