### PR TITLE
Update faraday version

### PR DESCRIPTION
**Pull request by kenneth1870ga**
As part of some compatibilities we need to update  gem `faraday`

### CODE REVIEW

**Comment by hakusaro** [comment]
@kenneth1870ga thank you for this! I don't work at instructure but I appreciate this!

**Comment by slaughter550** [comment]
@kenneth1870ga can you rebase this on master? Will be happy to take a look!

**Comment by bjbatten** [comment]
@slaughter550 @kenneth1870ga will this be moving forward anytime soon? Thank you.

**Comment by ccutrer** [comment]
Done by #191

**Pull request closed without merging**
